### ISSUE TITLE
Einladung zu Org Absicht?

### ISSUE THREAD

**Issue by marpeter** [XeniaBrandenburg2288/XeniaB#1]
Hallo Xenia,

ich habe eine Einladung zur Org otto-ec von dir bekommen. Da ich meines Wissens nichts mit Otto zu habe frage ich: 

- war das ein Versehen
- war das ein Test oder
- ist ein anderer "marpeter" gemeint

?

Viele Grüße,
Markus Peter

**Comment by XeniaBrandenburg2288** [comment]
Hallo Marcus,

vielen Dank für Deine Nachricht.

Aufgrund eines systemischen Fehlers wurde dir diese Einladung zugesendet. Entschuldige bitte die dadurch entstandenen Unannehmlichkeiten. Die Einladung wurde nun gelöscht.

Viele Grüße
Xenia

Von: marpeter <notifications@github.com>
Antworten an: XeniaBrandenburg2288/XeniaB <reply@reply.github.com>
Datum: Mittwoch, 11. November 2020 um 20:06
An: XeniaBrandenburg2288/XeniaB <XeniaB@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [XeniaBrandenburg2288/XeniaB] Einladung zu Org Absicht? (#1)


Hallo Xenia,

ich habe eine Einladung zur Org otto-ec von dir bekommen. Da ich meines Wissens nichts mit Otto zu habe frage ich:

  *   war das ein Versehen
  *   war das ein Test oder
  *   ist ein anderer "marpeter" gemeint

?

Viele Grüße,
Markus Peter
